### ISSUE TITLE
Impossible to run with different system user

### ISSUE THREAD

**Issue by ITspirit** [elements-at/ProcessManager#10]
The Function 
\Pimcore\Tool\Console::checkExecutingUser(); 
allows to pass an array with allowes users to execute.
Within ProcessManager in the Trait these function is been called at Line 114 within "initProcessManager"

In the Sample Command there is an additional call to the same method.
There i've the option to pass more differente users like:

        \Pimcore\Tool\Console::checkExecutingUser(['www-data', 'deployer', 'vagrant']);

Would make sense to give the option to initProcessManager, maybe in this manner:

```php
$allowedUsers = isset($options['allowedUsers']) && is_array($options['allowedUsers']) ? $options['allowedUsers'] : [];
unset($options['allowedUsers']);
........
\Pimcore\Tool\Console::checkExecutingUser($allowedUsers);
```

**Comment by ckogler-elements** [comment]
Hi,

thx for the hint with the sample command - it was redundant so i removed it from the SampleCommand.

I think we could define the users which are allowed to execute the processes globally - so we don't have to define them on each command. What do you think? 

As in https://github.com/elements-at/ProcessManager/commit/820f28c6a032e113fb62128b40bb048691f1d96f you would just have to add the users in the "additionalScriptExecutionUsers" config parameter.

**Comment by ITspirit** [comment]
The global define makes sense, sure. Makes it a lot easier to define.
Great 👍
