### ISSUE TITLE
Cancelling process throws error in Pimcore X

### ISSUE THREAD

**Issue by VeiJar1** [elements-at/ProcessManager#105]
Error traceback: "Timestamp: Wed Jul 07 2021 11:56:55 GMT+0300 (Eastern European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/elementsprocessmanager/monitoring-item/cancel
Method: get
Message: Attempted to call an undefined method named "exec" of class "Pimcore\Tool\Console".
Did you mean to call "execInBackground"?
Trace: 
in /var/www/html/vendor/elements/process-manager-bundle/src/Model/MonitoringItem.php:955"

It stops the process, but it gives an unnecessary error to user. 

This happens because in Pimcore X `Pimcore\Tool\Console::exec()` method has been removed. Use Symfony\Component\Process\Process instead.'

So I fixed it by this:
`public function stopProcess(){
        $pid = $this->getPid();
        if($pid){
            $this->setPid(null)->setStatus(self::STATUS_FAILED)->save();
		$process = new Process(['kill', '-9', $pid]);
		$process->run();
		// executes after the command finishes
		if (!$process->isSuccessful()) {
			throw new ProcessFailedException($process);
		}
            return !$this->isAlive();
        }
    }`

at /var/www/html/vendor/elements/process-manager-bundle/src/Model/MonitoringItem.php:951 - 964

also included 
`use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;
` 
in the same file

PS. Sorry for my indentations, not really sure how to make them here in Markdown...

**Comment by ckogler-elements** [comment]
Hi,

thx for the hint. I think it got fixed allready in the master branch, but it wasn't released with 4.0.0. With v4.0.1 it should work now.

Regards,
Christian
