### ISSUE TITLE
ERROR: call to undefined method Pimcore\Mail::setTextBody()

### ISSUE THREAD

**Issue by Jimerson21** [elements-at/ProcessManager#106]
Hello, 

elements/process-manager-bundle: "^4.0"

I have the following error in Pimcore X (10.0), apparently this method does not exist in Pimcore\Mail, it has the wrong name, it should be setBodyText.

![image](https://user-images.githubusercontent.com/58362749/127371210-0bb4b371-4889-42d3-994b-d0c04c85c6dd.png)

Error located in ProcessManager/src/Executor/Logger/EmailSummary.php:

![image](https://user-images.githubusercontent.com/58362749/127371308-71ff4883-88d3-4b4f-acce-8a4f8989e5a7.png)

**Comment by ckogler-elements** [comment]
Thx,

ist fixed in the latest releas.

Regards,
Christian
