### ISSUE TITLE
Getting Error while executing command.

### ISSUE THREAD

**Issue by utkarsh-sharma-511** [elements-at/ProcessManager#114]
Hello,

When I execute the Process manager command, I get below error:

![Screenshot_1](https://user-images.githubusercontent.com/88316749/133030200-adc3f599-e4c6-45df-8ad2-ad05e752db47.png)

Below is the configuration I have created in Process Manager:

![Screenshot_2](https://user-images.githubusercontent.com/88316749/133030281-f6e2bceb-dbad-4b56-b12b-aa176101d776.png)

Please assist me in resolving this issue. Also, please correct if anything I did wrong here.

**Comment by ckogler-elements** [comment]
Hi,

the settings looks ok - Can you execute die command directly in the shell?
Do you use this "COM" class somewhere in your code? 

Regards,
Christian

**Comment by utkarsh-sharma-511** [comment]
Hello Christian, 

Thanks for the reply.
Yes I can run the die command directly from shell.
I have not used "COM" class somewhere. I believe it is part of the bundle's code.
 
Regards,
Utkarsh

**Comment by ckogler-elements** [comment]
Hi,

can you debug the Elements\Bundle\ProcessManagerBundle\Helper::executeJob() method? Somewhere in there it seems to occure. The Bundle normaly doesn't use a "COM" class. 

Regards,
Christian
