### ISSUE TITLE
Monitoring Item deleteAfterHours property is always setting to 1

### ISSUE THREAD

**Issue by siddharth-chaudhery** [elements-at/ProcessManager#115]
The following line in Helper.php is not setting the correct value due to incorrect syntax. Its always setting the value as true. 

`$monitoringItem->setDeleteAfterHours(isset($executorData['values']['deleteAfterHours']) ?: null);`

**Comment by siddharth-chaudhery** [comment]
Created a PR for it #116

**Comment by ckogler-elements** [comment]
Fixed. Thx for the hint and PR
