### ISSUE TITLE
How to upgrade from 3 to 4?

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [elements-at/ProcessManager#129]
We updated to Pimcore 10 and so had to upgrade also the process manager. As the tables got renamed the old jobs are not used anymore. I tried to import the data from `plugin_process_manager_configuration` to `bundle_plugin_process_manager_configuration`. This is more complex than necessary as you have changed to order of columns...

Is there some instructions anywhere how to upgrade this bundle from 3 to 4?

PS: Ok, got it working. For others, here is the SQL to be executed:
```mysql
insert into bundle_process_manager_configuration 
SELECT `id`, `creationDate`, `modificationDate`, `name`, `group`, `description`, `executorClass`, `cronJob`, `lastCronJobExecution`, `active`, `keepVersions`, `action`, `executorSettings`, `restrictToRoles` FROM plugin_process_manager_configuration 
ON DUPLICATE KEY UPDATE bundle_process_manager_configuration.name=concat(plugin_process_manager_configuration.name,'2');
```

**Comment by ckogler-elements** [comment]
Hi,

upgrade instructions can be found here https://github.com/elements-at/ProcessManager/blob/master/doc/migration.md 

I guess the problem is, that renaming of the table was not done before running the installer on Pimcore X.

Regards,
Christian

**Comment by BlackbitNeueMedien** [comment]
Ok, but why isn't there a migration which renames the table automatically?

Also the command `pimcore:bundle:update` does not exist anymore, see https://github.com/elements-at/ProcessManager/blob/ed3b15fe0c99b91a569d621b9c1204fafdecbccd/doc/migration.md?plain=1#L34 
I do not what the concept for bundle updates with Pimcore 10 is. For our own bundles we use the `pimcore:bundle:install` command for this now because the command to execute migrations (bin/console doctrine:migrations:migrate --prefix=Namespace\\of\\bundle) is too complicated imho.

**Comment by mysliwietzflorian** [comment]
I also ran into the problem with `picore:bundle:update`. Simply used doctrine-migrations with
- `php bin/console doctrine:migrations:list` -> I saw *Version20210802000000* was not migrated
- `php bin/console doctrine:migrations:migrate 'Elements\Bundle\ProcessManagerBundle\Migrations\Version20210802000000'`

Worked for me.

**Comment by ckogler-elements** [comment]
Thx - i updated the docs.

`
./bin/console doctrine:migrations:migrate --prefix=Elements\\Bundle\\ProcessManagerBundle 
`
should work.
