### ISSUE TITLE
Action and Logger buttons not working in Pimcore v5.3.1

### ISSUE THREAD

**Issue by psuhane** [elements-at/ProcessManager#13]
Action and Logger buttons not working in Pimcore v5.3.1 while adding/editing process setting. Please refer following screen

![screenshot-ereactor local-2019 01 20-21-51-47](https://user-images.githubusercontent.com/12061880/51441982-c80b5400-1cfd-11e9-9a72-3e401c2e8998.png)

**Comment by ckogler-elements** [comment]
Hi,

hmm.. strange. 

Do you have entries in "executorLoggerClasses" and "executorActionClasses"  when you call the URL /admin/elementsprocessmanager/index/get-plugin-config?_dc=1548057952941 

It should look like this:
![image](https://user-images.githubusercontent.com/8791970/51460608-3848c280-1d5c-11e9-82fa-97e272079385.png)

Is it a fresh instlallation or die you updated the ProcessManager?

**Comment by psuhane** [comment]
@ckogler-elements - yes the config is working on get-plugin-config fine. But plus button not working for logger and executor.

Yes.. installing fresh ProcessManager on Pimcore instance(v5.3.1).

**Comment by ckogler-elements** [comment]
Do you get any Javascript Error in the console?

Do you see the "Download" Button if you click on the  "+"?
![image](https://user-images.githubusercontent.com/8791970/51475644-50800800-1d83-11e9-8e92-a817ee05b0b0.png)

**Comment by psuhane** [comment]
Yes, there is a js issue coming in the console - 

Ext.data.reader.Reader: Using the deprecated "root" configuration. Use "rootProperty" instead.

and I tried to fix it by changing root to rootProperty in abstractExecutor.js and still it didn't worked.

**Comment by ckogler-elements** [comment]
I notices that the updater/installer created a wrong array structure for the executorLoggerClasses. 

Could you please try to replace the content of your plugin-process-manager.php with this one:

https://github.com/elements-at/ProcessManager/blob/master/src/Elements/Bundle/ProcessManagerBundle/install/plugin-process-manager.php

I tried it with a 5.2.2 and it worked after i altered the config... What Browser are you using? Chrome?
