### ISSUE TITLE
Restrict to Roles not saved

### ISSUE THREAD

**Issue by NiklasBr** [elements-at/ProcessManager#131]
Pimcore: 10.2.5
Process Manager: 4.0.7

1. Create a process in the UI
2. Close/save it
3. Open it again
4. Chose one or more roles to restrict it to
5. Close/save it
6. Open it again

Actual Result: the selected roles are no longer selected.

Expected: The selected roles should remain selected.

**Comment by ckogler-elements** [comment]
Hi,
the fix attached should fix this.
Thx for reporting.

Regrads,
Christian
