### ISSUE TITLE
Edit/save command fails

### ISSUE THREAD

**Issue by valentin-** [elements-at/ProcessManager#132]
It's not possible to open an existing command and save it. It's trying to insert a new recording instead of updating the record.

![image](https://user-images.githubusercontent.com/90033/144252958-e505817a-b180-4816-bc37-8cabd4bd60d7.png)

**Comment by ckogler-elements** [comment]
Hi, 
the commit attached should solve the issue.

thx for reporing it.

Regards,
Christian
