### ISSUE TITLE
Cronjob not working for pimcore commands

### ISSUE THREAD

**Issue by utkarsh-sharma-511** [elements-at/ProcessManager#136]
I am trying to schedule a command to run from cron but it is not working.
Though the next run command time is correct but it is not running at that time and the time is not getting updated.
I am able to execute the cpmmand manually.
![Screenshot_5](https://user-images.githubusercontent.com/88316749/147225423-ad07ec5b-9e81-4e19-a088-d41aea4f7647.png)
![Screenshot_6](https://user-images.githubusercontent.com/88316749/147225431-4b488ae5-ea13-47ec-9e6c-a775bd2d61e9.png)
.

**Comment by ckogler-elements** [comment]
Hi,
have you set up the cronjob 

* * * * * php ~/www/bin/console process-manager:maintenance > /dev/null 2>&1

as mentioned in https://github.com/elements-at/ProcessManager/blob/master/doc/installationAndUpdates.md ?

This should trigger the execution.

Regards,
Christian

**Comment by utkarsh-sharma-511** [comment]
Hi Christian,
Yes I have added the cron.

**Comment by NiklasBr** [comment]
Can reproduce this issue as well, with the following example command which generates some thumbnails, no errors appears as far as I can find.

```php
class AssetThumbnailGenerationCommand extends AbstractCommand
{
    use ExecutionTrait;

    protected function configure()
    {
        $this->setName('app:assets:generate-thumbnails');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $monitoringItem = $this->initProcessManager(3600);

        // Real command has multiple folders and multiple sets of thumbnail configs, this is simplified
        $folders = Folder::getByPath('/');
        $monitoringItem->setTotalSteps(count($folders))->setMessage('Starting process')->save();

        $phpPath = (new PhpExecutableFinder())->find() ?? Console::getPhpCli();

        $folder = Asset\Folder::getById($folderId);

        $arguments = [
            $phpPath,
            PIMCORE_PROJECT_ROOT . '/bin/console',
            'pimcore:thumbnails:image',
            "--thumbnails=treePreview,wysiwygEmbed",
            "--parent={$folderId}",
            "--no-ansi",
            "--no-interaction",
        ];

        $output->writeln("{$this->getName()} starting command: " . implode(' ', $arguments));
        $monitoringItem->setMessage("Processing {$folder->getFullPath()}")->setCurrentStep(1)->save();

        $process = new Process($arguments);
        $process->setTimeout(3600);
        $process->setWorkingDirectory(PIMCORE_PROJECT_ROOT);
        $output->writeln("{$this->getName()} processing {$folder->getFullPath()}");

        $resultCode = $process->run();
        $process->stop(10, $resultCode);

        $monitoringItem->setMessage('Job finished')->setCompleted();
        return self::SUCCESS;
    }
}
```

**Comment by utkarsh-sharma-511** [comment]
There was a permission Issue.

**Comment by NiklasBr** [comment]
@utkarsh-sharma-511 did you resolve this? What was the solution?

**Comment by betterapp** [comment]
@utkarsh-sharma-511 I have the same issue. Process Manager stuck and do nothing since 5 days now.
![image](https://user-images.githubusercontent.com/7449124/204749187-f95ea1be-3c1b-4061-9466-34e7b907a009.png)
