### ISSUE TITLE
Updating user for additionalScriptExecutionUsers

### ISSUE THREAD

**Issue by moiashvin** [elements-at/ProcessManager#137]
Hi,

Can you please help to add the configuration for additionalScriptExecutionUsers in the yaml file.

I am using Pimcore 10.2, from bitnami. The cron jobs of Pimcore are configured to user daemon to execute.

I had added the following in the services.yaml but it's not working.

#bitnami uses daemon for cron jobs
elements_process_manager:
    additionalScriptExecutionUsers : ["daemon"]

services:
    ....
    ...

If i dump the configuration, 

elements_process_manager:

    # Defines how many days log entries are kept
    archiveThresholdLogs: 7

    # If the MonitoringItem has not been save within X minutes it will be considered as hanging process
    processTimeoutMinutes: 15

    # Disable the shortcut menu on the left side in the Pimcore admin
    disableShortcutMenu:  false

    # Defines email addresses to which errors should be reported
    reportingEmailAddresses: []

    # Defines additional system users which are allowed to execute the php scripts
    additionalScriptExecutionUsers:

        # Default:
        - sdfasdfad@asdfasdf.com
    restApiUsers:

        # Prototype
        -
            username:             ~ # Required
            apiKey:               ~ # Required

Can you help so I can add the daemon user in list.

Thanks

**Comment by ckogler-elements** [comment]
Hi,

elements_process_manager:
    additionalScriptExecutionUsers : ["daemon"]

sould be fine. I just noticed that in the docs "config:dump-reference" was used.

Can you execute 
bin/console debug:config ElementsProcessManagerBundle

there you should see the deamon user.

Regards,
Christian

**Comment by ckogler-elements** [comment]
Maybe you have to clear the cache?

**Comment by moiashvin** [comment]
Thank you, it's good.
