### ISSUE TITLE
Inactive tab text color

### ISSUE THREAD

**Issue by passioneight** [elements-at/ProcessManager#139]
It's really hard to see the text in the inactive tabs:

![image](https://user-images.githubusercontent.com/57256630/150993396-29fa8862-32cf-4c4e-afa5-b25fde4e2448.png)

**Comment by ckogler-elements** [comment]
Hi,
thx for the hint - maybe i know the ProcessManager too good so i don't need to read the names anymore - or they changed the colors :-). 

This is fixed in the latest version.

Best regards

**Comment by passioneight** [comment]
@ctippler I just installed the latest version on Pimcore 10.4.4:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/57256630/175956125-fe008fa7-3c2c-4d72-971a-d8c6231e9d9f.png">

Seems like Pimcore changed the background color... can you change once more?

**Comment by NiklasBr** [comment]
I also noticed the lost background on inactive tabs, could have sworn I saw a fix a while ago, so assumed it was just me :)

**Comment by ctippler** [comment]
PR would be welcome ;-)
