### ISSUE TITLE
How to: Write Bundle with Callback Extension

### ISSUE THREAD

**Issue by ITspirit** [elements-at/ProcessManager#144]
Just a question, not a Issue:

I have a bundle with the processManager as a dependency.
The bundle comes with a callback definition.

How can i extend the ProcessManager Configuration through the bundle (to add the executorCallbackClasses).

I´ve tried it like defined by Symfony (create a Extension with a PrependExtensionInterface), but it looks it doesn´t work.

Any suggestions?

**Comment by ckogler-elements** [comment]
Hi,
i guess you could just define them in your services.yaml of your bundle - at least the processmanger by itself does it this way 
![image](https://user-images.githubusercontent.com/8791970/159000079-dfa52e65-e991-41b1-854b-7107fe1de059.png)

Regards,
Christian
