### ISSUE TITLE
TabPanels invalid background color

### ISSUE THREAD

**Issue by elements-team** [elements-at/ProcessManager#153]
Most panels in Pimcore now have the wrong background color. 

@NiklasBr as far as I saw the bug was introduced in 9b809bf

![image](https://user-images.githubusercontent.com/21100616/185625129-9736b547-102d-46d5-a162-34733b1dcd96.png)

**Comment by NiklasBr** [comment]
@elements-team the selector seems to be the old one still (it is partially obscured though), the new one should be `#pimcore_plugin_pm_panel-bodyWrap > .x-tab-bar > .x-tab-bar-body`. Please verify.
