### ISSUE TITLE
Possibility of batch execution of multiple commands

### ISSUE THREAD

**Issue by galum** [elements-at/ProcessManager#154]
General Question: Is there a way, or what is the best way, to execute multiple commands in batch mode, directly one after another, as a single cronjob or single manual execution? For example, there may be be commands which depend on an other command being executed before, and where unnecessary delay is to be avoided.

**Comment by ctippler** [comment]
Hi,
well there are different aproaches depending on the specific need. I tried to summarize it in https://github.com/elements-at/ProcessManager/blob/master/doc/batchCommandExecution.md  

Regards,
Christian

**Comment by galum** [comment]
Hello Christian, thank you very much for your quick reply and your efforts. Our current solution has been to use a shell script, but the GroupExecutionCommand sample looks promising. 

Thank you
