### ISSUE TITLE
Job execution by user doesn't work

### ISSUE THREAD

**Issue by yeti3180** [elements-at/ProcessManager#168]
I've updated to ProcessManager 4.1.1 and Pimcore 10.5.17 and did all migrations.
Job execution by user doesn't work, only cronjobs are running.
I can't find any error in the logs.

**Comment by MMierzynski** [comment]
I have the same issue:
- ProcessManager: 4.1.1
- Pimocre 10.5.17

**Comment by ctippler** [comment]
Can you please provide more information? Do you see the jobs in the admin panel and they don't start when you click on execute? If yes -> please check if the xhr request in the network panel returns an error?

Regards,
Christian

**Comment by yeti3180** [comment]
> Can you please provide more information? Do you see the jobs in the admin panel and they don't start when you click on execute? If yes -> please check if the xhr request in the network panel returns an error?
> 
> Regards, Christian

Hi Christian,

nothing happens when you click on execute (green arrow) in the admin panel nor the shortcut menu.
xhr request = admin/elementsprocessmanager/config/get-by-id?id=1&_dc=1677153727401 and gets status 200
usually execute follows, but not in this case

`{success: true, data: {id: 1, name: "test", group: "", description: "", creationDate: 1676993540,…}}
data: {id: 1, name: "test", group: "", description: "", creationDate: 1676993540,…}
  active: true
  creationDate: 1676993540
  cronJob
: 
""
description
: 
""
executorClass
: 
"Elements\\Bundle\\ProcessManagerBundle\\Executor\\PimcoreCommand"
executorClassObject
: 
null
executorSettings
: 
{values: {id: "1", name: "test", group: "", description: "", restrictToRoles: "0", callback: "",…},…}
actions
: 
[]
loggers
: 
[]
values
: 
{id: "1", name: "test", group: "", description: "", restrictToRoles: "0", callback: "",…}
callback
: 
""
command
: 
"export-toolkit:export"
commandOptions
: 
"--config-name=\"Magento_Articledata\""
cronjob
: 
""
defaultPreDefinedConfig
: 
""
deleteAfterHours
: 
""
description
: 
""
group
: 
""
id
: 
"1"
keepVersions
: 
""
name
: 
"test"
restrictToRoles
: 
"0"
group
: 
""
id
: 
1
keepVersions
: 
null
lastCronJobExecution
: 
null
modificationDate
: 
1676993540
name
: 
"test"
restrictToPermissions
: 
null
restrictToRoles
: 
",0,"
success
: 
true`

**Comment by ctippler** [comment]
Hi,
the issue seems to occure when no callback window is defined. Could you please update to v4.1.2 - this should fix the issue.

Regards,
Christian

**Comment by MMierzynski** [comment]
@ctippler works well. Thanks for the fast action

**Comment by yeti3180** [comment]
Thanks!
