### ISSUE TITLE
No Download and OpenItem actions for jobs with status finished_with_errors

### ISSUE THREAD

**Issue by APochmann** [elements-at/ProcessManager#172]
Only for jobs with STATUS_FINISHED it's showing buttons for Download and OpenItem action. There are use cases where this would also be good to be allowed in status STATUS_FINISHED_WITH_ERROR, e.g. if there is a log file which gives hints to fix the issue causing the error.
I've already created a pull request #169 to solve the issue. This implements an additional configuration item to switch between existing and new behaviour. Better description can be found in pull request but as this was ignored until now I thought it would be a good idea to create an issue also 😉

**Comment by ctippler** [comment]
Hi,
thank you very much for the PR request and the effort to adopt it. The changes are in the release v4.3.0 .

Regards,
Christian
