### ISSUE TITLE
Role restriction not working

### ISSUE THREAD

**Issue by moiashvin** [elements-at/ProcessManager#176]
I'm having an issue with restricting the process to specific role so only users in that code can see / trigger it.

pimcore version v10.5.20
elements/process-manager-bundle v4.0.23

To reproduce issue,
Create 2 roles in Pimcore (ROLE_A and ROLE_B)
Create 2 users in Pimcore (USER_A and USER_B) 
Assign each user to the specific role - USER_A to ROLE_A and USER_B to ROLE_B
Create a process in the Process Manager and in "Restrict to Roles", choose ROLE_A

Now, if I login as USER_B, I can see the process from the side menu and I can even run the process (even if that process was for users in ROLE_A only)

Can anyone advise how this can be fixed.

**Comment by ctippler** [comment]
Hi,
the version v4.3.1 should fix this issue. An update from v4.0.23 to v4.3.1 should work well as long as you execute the migrations after the composer update.

./bin/console doctrine:migrations:migrate --prefix=Elements\\Bundle\\ProcessManagerBundle 

Regards,
Christian
