### ISSUE TITLE
 Attempted to load trait "StateHelperTrait" from namespace "Pimcore\Extension\Bundle\Traits".     Did you forget a "use" statement for another namespace?           

### ISSUE THREAD

**Issue by lp741** [elements-at/ProcessManager#186]
I can't install the bundle beacause I received this error

 Attempted to load trait "StateHelperTrait" from namespace "Pimcore\Extension\Bundle\Traits".  
  Did you forget a "use" statement for another namespace?           
  
  It seams that StateHelperTrait has been removed in last version of 11.0.6

**Comment by ctippler** [comment]
Hi,
i guess you have not used the master branch to install the processmanger? We currently had no release version for pimcore 11. I Just created a Version 5.0.0 which should work for Pimcore 11. The StateHelperTrait is not used in this version.

Regards,
Christian

**Comment by lp741** [comment]
Seems forcing package version to 5 worked fine

**Comment by ziggurad** [comment]
@lp741 did you have any problems after using version 5? I mean something similar to what I described here https://github.com/elements-at/ProcessManager/issues/187 ?
