### ISSUE TITLE
Permission error thrown on every admin page load for admins without PM view

### ISSUE THREAD

**Issue by tmannherz** [elements-at/ProcessManager#188]
We have a number of Pimcore admin roles configured in our system that do not get access to any of the Process Manager permissions, so these are all unchecked:
![image](https://github.com/elements-at/ProcessManager/assets/533798/28c9c330-f462-4735-9f2e-230a09ddb69e)

When loading any page in the admin, the following error popup is generated:
![image](https://github.com/elements-at/ProcessManager/assets/533798/2757f0b5-2413-49e9-a358-4f67789e0fac)

The source is an admin plugin check request, `/admin/elementsprocessmanager/index/get-plugin-config?_dc=1694452251588`

I can trace the error to [this line in the IndexController](https://github.com/elements-at/ProcessManager/blob/master/src/Controller/IndexController.php#L34):

```php
    #[Route(path: '/get-plugin-config')]
    public function getPluginConfigAction(CommandsValidator $commandsValidator, Translator $translator): JsonResponse
    {
        $this->checkPermission(Enums\Permissions::VIEW);
```

Since this plugin check is called on every admin page load, it should return successfully rather than throwing an exception, similar to how other Pimcore permission checkers do:

```php
    #[Route(path: '/get-plugin-config')]
    public function getPluginConfigAction(CommandsValidator $commandsValidator, Translator $translator): JsonResponse
    {
        try {
            $this->checkPermission(Enums\Permissions::VIEW);
        } catch (AccessDeniedHttpException $e) {
            Logger::log('[Startup] Process Manager is not loaded as "plugin_pm_permission_view" permission is missing');

            //return to avoid error on startup
            return $this->jsonResponse([]);
        }
```

Running Pimcore v11.0.8 and 5.0 of the process manager bundle.

**Comment by ctippler** [comment]
Thx - It's fixed in v5.0.1.
Best regards,
Christian
