### ISSUE TITLE
Wrong order of processes in popup when new jobs to be added

### ISSUE THREAD

**Issue by APochmann** [elements-at/ProcessManager#191]
## Problem
An update of the ExtJS Toast popup window which lists the jobs will show a wrong order in case there is more than on job entry to be added.
## Example
 If current list would show (strictly descending)
```
some-job (id 3)
some-job (id 2)
some-job (id 1)
```
and a call of JS function `requestServerData()` returns (which is also strictly descending)

```
{
    "total": 5,
    "active": 0,
    "items": [
        {
            "id": 5,
...
        },
        {
            "id": 4,
...
        },
        {
            "id": 3,
...
        },
        {
            "id": 2,
...
        },
        {
            "id": 1,
...
        }
```
the result will be (note that the first two entries are shown in wrong order)
```
some-job (id 4)
some-job (id 5)
some-job (id 3)
some-job (id 2)
some-job (id 1)
```
## Reason
In the current implementation of the success function of the Ajax call there is a loop calling `_buildBar` on all items of the web call result which updates the existing panel or creates a new one on the top. In the example above it is first called for item 5 and creates in on the top and then for item 4 and creates it on the top again (before item 5). Result is a wrong order.

## Proposal
Maybe it would be good to modify that loop to only call `_buildBar` for existing entries and cache the new ones. Once this loop is done the cache can be executed in reverse order and all entries will be on correct place

**Comment by APochmann** [comment]
Hi @ctippler , I could provide a PR for the topic above and would even like to combine with two other requests. Let me give you some information on this:

I've implemented import/export using the ProcessManager and the users keep the entries in the job list to have access to the log files created. This is the reason why they have rather long lists and these take long time to be updated (> 10 seconds). Now this results in three issues which I would solve at once:

1. Wrong order of processes in popup when new jobs to be added (described above)
2. "Loading..." spinner mask while updating the list
here I would mask the toast content (list of the jobs) and show a "loading..." message in the same way as it is used for grid loading
4. Configurable refresh times instead of the 3 seconds default
here I introduce a new configuration item which defaults to 3 seconds (current static value) but can be set to other values

please let me know if these are acceptable changes and if I should create a single PR for that or you request them separatly

**Comment by ctippler** [comment]
Hi,

well, 1 and 3 are totally fine. Depending Point 2: I personally wouldn't mask it because i think it can become quite annoying when it "blinks/reloads" every 3 seconds. But we could try it and then check how it looks/feels. 

I think one PR is totally fine. But generally they should not keep that much processes in the Toast panel. 
The can always go to "Extras -> ProcessMangager -> Process Log" to see old exports... and there they can filter...

Regards,
Christian

**Comment by APochmann** [comment]
Hi @ctippler ,

thanks for the response and I totally understand the concerns about the spinner so I did some more tests and measures and have some serious issues:

1. During the update of the toast based on the list from backend the UI is blocked
Although I was thinking this is caused by the spinner it turned out that the complete window is not responsive during updating the panels per job in toast independent of having a spinner or not. In the current implementation you will just recognize that the UI does not react without any indication (I simply moved the mouse up and down the object tree to hoover the elements and even that hoovering stopped during toast update)
2. Updating the elements takes much more time than creating them
When I calculated the average runtime for creation/update of a single entry in the list (used a long list with 50 entries to calculate average time) I had 2,4485 ms for creation and 487,926 ms for the update which is factor 200! This also means that pimcore had not responsive UI for more than 20 seconds in case just a single job in the long list is active.

I understood that this might be wrong usage of the toast panel but this still seems to be a problem to me. When checking the different tasks during the update it turned out that nearly all the time was used for `this._updateActionBtns`. Without this check the average update time in my testscase was 0,6377 ms instead of 487,926 ms. Maybe I miss a point, but why should the action items change after a job is not active anymore? When adding a check, if the current item in the list (before update) was already inactive I had that nearly 500 ms blocking only for active items and that seemed to be acceptable.

**Comment by APochmann** [comment]
Found the reason for action update which I missed before: The referenced object or file might be deleted which will disable the button! So a more detailed check is needed to determine if panel update is required. I will prepare a PR now without spinner but with check to update only panels which require change
