### ISSUE TITLE
Exception when using ProcessManagerBundle\ExecutionTrait::executeChildProcesses

### ISSUE THREAD

**Issue by muratbinerbay** [elements-at/ProcessManager#194]
Looks like when a child process is executed by calling `executeJob` on `ProcessManagerBundle\ExecutionTrait::executeChildProcesses` the metadata being passed is still a string because of `json_encode`.

I assume the `json_encode` can be removed in this case?

`Elements\Bundle\ProcessManagerBundle\Model\MonitoringItem::setMetaData(): Argument #1 ($metaData) must be of type array, string given, called in /var/www/html/vendor/elements/process-manager-bundle/src/Helper.php on line 57 `

**Comment by muratbinerbay** [comment]
Opened https://github.com/elements-at/ProcessManager/pull/197 to fix the issue

**Comment by ctippler** [comment]
Merged,
thx
