### ISSUE TITLE
Generated migrations do not work

### ISSUE THREAD

**Issue by ziggurad** [elements-at/ProcessManager#196]
Migrations generated by the `process-manager:migrations:generate` command do not work:

```
Error thrown while running command "'d:m:m' -n". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group = 'cron', description = '', executorClass = 'Elements\\Bundle\\Process' at line 1"
```
The reason is the group field.

More here: 
https://stackoverflow.com/questions/23446377/syntax-error-due-to-using-a-reserved-word-as-a-table-or-column-name-in-mysql

**Comment by ctippler** [comment]
Hi, this should be fixed with the latest version.

Regards,
Christian
