### ISSUE TITLE
How to avoid making objects versions

### ISSUE THREAD

**Issue by Kreolia** [elements-at/ProcessManager#198]
Hi,

My company uses this bundle to handle several tasks of import/export datas between our pim (Pimcore 10.5) and other applications. Some of them are made with another bundle named Data-Definitions, and some are CLI commands we developped.
In all cases, the import tasks make a new version of the objet (with the user named system of course), even the tasks with Data-definitions which has a option to avoid this.
For the CLI commands, I've tried to disable versionning temporarily as Pimcore documentation explain it (https://pimcore.com/docs/pimcore/10.5/Development_Documentation/Tools_and_Features/Versioning.html#page_Turn-off-Versioning-for-the-Current-Process) but it doesn't seem to work.

Can you help me to understand how we can update the objects without making this versions that pollute the history ?

Thanks

**Comment by ctippler** [comment]
Hi,

when you call  \Pimcore\Model\Version::disable(); no versions are saved afterwards as long as it isn't enabled somewhere in your code. 

If this dosn't work, maybe a pimcore Forum would be appropriate because this bundle has nothing to do with versions ;-)

Regards,
Christian
