### ISSUE TITLE
Duration time is wrong after setting the reportedDate

### ISSUE THREAD

**Issue by j-jonas** [elements-at/ProcessManager#22]
You calculate the duration time with the two database fields "creationDate" and "modificationDate", but when you are set the "reportedDate" you also set a new "modificationDate".
I think you need another field for an "endDate" or you are not allowed to change "modificationDate", if you only want to change the "reportedDate".

**Comment by AlternateIf** [comment]
the modification date should not be changed by the maintenance if the process is not alive anymore
