### ISSUE TITLE
Errors during installation on Pimcore 6 Skeleton

### ISSUE THREAD

**Issue by Pierre-Datasolution** [elements-at/ProcessManager#28]
Hi Elements team,

I just installed process-manager 3.0.0 on Pimcore 6 Skeleton
I have errors during bundle enable, bundle install and pimcore admin launching
var/config/plugin-process-manager.php is present

I paste here after the log

Thanks for your help
Pierre

**composer.json :**
	"elements/process-manager-bundle": "^3.0"

**Installing bundle :**
	# bin/console pimcore:bundle:list
	+---------------------------------+---------+-----------+----+-----+-----+
	| Bundle                          | Enabled | Installed | I? | UI? | UP? |
	+---------------------------------+---------+-----------+----+-----+-----+
	| ElementsProcessManagerBundle    | ❌       | ❌         | ❌  | ❌   | ❌   |
	| PimcoreEcommerceFrameworkBundle | ❌       | ❌         | ❌  | ❌   | ❌   |
	| TestingMoreBundle               | ❌       | ❌         | ❌  | ❌   | ❌   |
	+---------------------------------+---------+-----------+----+-----+-----+
	
	Legend: I?: Can be installed? UI?: Can be uninstalled? UP?: Can be updated?
	# bin/console pimcore:bundle:enable ElementsProcessManagerBundle
	
	
	 [OK] Bundle "Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle" was successfully enabled
	
	
	
	Running post state change commands
	----------------------------------
	
	 // Running bin/console assets:install...
	
	
	 Trying to install assets as relative symbolic links.
	
	 --- ------------------------------ ------------------
	      Bundle                         Method / Error
	 --- ------------------------------ ------------------
	  ✔   PimcoreCoreBundle              relative symlink
	  ✔   PimcoreAdminBundle             relative symlink
	  ✔   ElementsProcessManagerBundle   relative symlink
	 --- ------------------------------ ------------------
	
	
	 [OK] All assets were successfully installed.
	
	
	15:36:44 ERROR     [pimcore] ErrorException: Warning: include(/var/www/html/var/config/plugin-process-manager.php): failed to open stream: No such file or directory in /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/ElementsProcessManagerBundle.php:170
	Stack trace:
	#0 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/ElementsProcessManagerBundle.php(170): include()
	#1 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/Installer.php(29): Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle::getConfig()
	#2 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(559): Elements\Bundle\ProcessManagerBundle\Installer->isInstalled()
	#3 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/Traits/StateHelperTrait.php(60): Pimcore\Extension\Bundle\PimcoreBundleManager->isInstalled(Object(Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle))
	#4 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/SystemEventsListener.php(60): Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle::isInstalled()
	#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(126): Elements\Bundle\ProcessManagerBundle\SystemEventsListener->onConsoleTerminate(Object(Symfony\Component\Console\Event\ConsoleTerminateEvent), 'console.termina...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
	#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(260): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\Console\Event\ConsoleTerminateEvent), 'console.termina...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
	#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.termina...', Object(Symfony\Component\Console\Event\ConsoleTerminateEvent))
	#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(75): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'console.termina...', Object(Symfony\Component\Console\Event\ConsoleTerminateEvent))
	#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleTerminateEvent), 'console.termina...')
	#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(954): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleTerminateEvent), 'console.termina...')
	#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#12 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#14 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#15 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
	#16 {main}
	
	 // Running bin/console cache:clear...
	
	
	 // Clearing the cache for the dev environment with debug
	 // true
	
	
	 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
	
	
	# bin/console pimcore:bundle:install ElementsProcessManagerBundle
	*15:37:12 ERROR     [pimcore] ErrorException: Warning: include(/var/www/html/var/config/plugin-process-manager.php): failed to open stream: No such file or directory in /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/ElementsProcessManagerBundle.php:170
	Stack trace:
	#0 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/ElementsProcessManagerBundle.php(170): include()
	#1 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/Installer.php(29): Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle::getConfig()
	#2 /var/www/html/vendor/elements/process-manager-bundle/src/Elements/Bundle/ProcessManagerBundle/Installer.php(47): Elements\Bundle\ProcessManagerBundle\Installer->isInstalled()
	#3 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(522): Elements\Bundle\ProcessManagerBundle\Installer->canBeInstalled()
	#4 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(480): Pimcore\Extension\Bundle\PimcoreBundleManager->canBeInstalled(Object(Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle))
	#5 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/Bundle/InstallCommand.php(44): Pimcore\Extension\Bundle\PimcoreBundleManager->install(Object(Elements\Bundle\ProcessManagerBundle\ElementsProcessManagerBundle))
	#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(939): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#12 /var/www/html/bin/console(26): Symfony\Component\Console\Application->run()
	#13 {main}
	
	
	 [OK] Bundle "ElementsProcessManagerBundle" was successfully installed
	
	
	# bin/console pimcore:bundle:list
	+---------------------------------+---------+-----------+----+-----+-----+
	| Bundle                          | Enabled | Installed | I? | UI? | UP? |
	+---------------------------------+---------+-----------+----+-----+-----+
	| ElementsProcessManagerBundle    | ✔       | ✔         | ❌  | ❌   | ❌   |
	| PimcoreEcommerceFrameworkBundle | ❌       | ❌         | ❌  | ❌   | ❌   |
	| TestingMoreBundle               | ❌       | ❌         | ❌  | ❌   | ❌   |
	+---------------------------------+---------+-----------+----+-----+-----+
	
	Legend: I?: Can be installed? UI?: Can be uninstalled? UP?: Can be updated?
	#

**Launching pimcore admin or clicking Tools/Plugin button :**
	Server threw exception - could not perform action. Please reload the admin interface and try again.
	
	Timestamp: Wed Jun 26 2019 15:44:13 GMT+0200 (heure d’été d’Europe centrale)
	Status: 404 | Not Found
	URL: /admin/elementsprocessmanager/index/get-plugin-config
	Message: No route found for "GET /admin/elementsprocessmanager/index/get-plugin-config" (from "http://pimplaying6.local:8002/admin/")
	Trace: 
	#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(126): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
	#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(260): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
	#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
	#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(75): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
	#4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
	#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
	#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
	#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
	#8 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
	#9 {main}

**Comment by AlternateIf** [comment]
can you try and run the `bin/console process-manager:update -vv` command
let us know if this resolves your problem.

**Comment by Pierre-Datasolution** [comment]
# bin/console process-manager:update -vv
[2019-06-26 16:03:44] app.NOTICE:
[2019-06-26 16:03:44] app.DEBUG: Start update
[2019-06-26 16:03:44] app.NOTICE: Current Version:9
[2019-06-26 16:03:44] app.DEBUG: Finished update
[2019-06-26 16:03:44] app.NOTICE: finished

Solved the problem in Pimcore Admin AFTER pimcore:cache:clear and cache:clear

Thanks

**Comment by AlternateIf** [comment]
perfect. alternatively you could have called pimcore:bundle:install or enabled/installed the bundle from the bundles tab in the admin interface.  This would've created the default process-manager config too.
