### ISSUE TITLE
Bad test on file owner when root

### ISSUE THREAD

**Issue by FredoVelcro** [elements-at/ProcessManager#40]
Using a docker env, my system.yml file owner is root (ID 0) so the test is bad in that case :

https://github.com/elements-at/ProcessManager/blob/8feeb2086233a1c55c236945bb16a43e1e0ea6a5/src/ExecutionTrait.php#L196

Test should be strict : 

```php
if ($owner === false) {
```

see https://www.php.net/manual/fr/function.fileowner.php#98627

tested, it is now ok

**Comment by ckogler-elements** [comment]
thx - fixed it
