### ISSUE TITLE
MonitoringItem::getCallbackSettings() : json_decode fails as settings can be empty array

### ISSUE THREAD

**Issue by FredoVelcro** [elements-at/ProcessManager#44]
https://github.com/elements-at/ProcessManager/blob/0905cd66ac07318d3eaa35ab4bea580d2d419ef0/src/Model/MonitoringItem.php#L703

As it is declared line 86 as :
```php
public $callbackSettings = [];
```

it fails when calling MonitoringItem->getCallbackSettings() : 
```
 Warning: json_decode() expects parameter 1 to be string, array given
```

**Comment by ckogler-elements** [comment]
thx. Fixed

**Comment by FredoVelcro** [comment]
back again !
Big regression !
Should have handled the fact that it could be either an array or a string :

**Comment by FredoVelcro** [comment]
Something like this : 
```php
    /**
     * @return array
     */
    public function getCallbackSettings()
    {
        return is_string($this->callbackSettings) ? json_decode($this->callbackSettings) : $this->callbackSettings;
    }
```
