### ISSUE TITLE
Progress Bar issue

### ISSUE THREAD

**Issue by subhash8785** [elements-at/ProcessManager#93]
There are no option to pass the parameter for the background command . and if we overwrite the method to execute the command then progress bar is not working.

**Comment by ckogler-elements** [comment]
Hi,

custom Command paramters can be defined in the "Command options" field:
![image](https://user-images.githubusercontent.com/8791970/113837008-b521b480-978d-11eb-9118-375f615e9a69.png)

With this configuration the following command would be executed:
./bin/console app:dev --testparam1=test1 --param2=value

Ist this what you are looking for?
Regards,
Christian
