### ISSUE TITLE
Should use job ID from job object

### ISSUE THREAD

**Issue by FredoVelcro** [elements-at/ProcessManager#94]
Hello,

As the Job could be looked up by name or id (via the Request), in case of getting it by "name" will fail here :

https://github.com/elements-at/ProcessManager/blob/47a31bbb494b1ba94248f51443a70a9928a3ea39/src/Controller/RestController.php#L108

should be something like :

```php
$result = Helper::executeJob($config->getId(), $callbackSettings, $user->getId());
```

**Comment by ckogler-elements** [comment]
Hi,
absolutely right. Is changed.

Thx
