### ISSUE TITLE
Unable to install on a fresh Pimcore X Installation

### ISSUE THREAD

**Issue by ITspirit** [elements-at/ProcessManager#98]
On a fresh PimcoreX installation, it´s not possible to enable Processmanager.

On CLI it shows "Base table or view not found: 1146 Table 'bundle_process_manager_monitoring_item' doesn't exist"

Seems, that the installtion process has failed and hasn´t created the required Database Table.

After creating the tables manually, i will be able to enable/disable the bundle without errors, but there is still no sign of the presence of the bundle. It´s completely invisible (but no errors in the console)

**Comment by ckogler-elements** [comment]
Hi,
thx for the hint. Could you please try it again with the latest "master" version. 
Should work now... 
Regards,
Christian

**Comment by ITspirit** [comment]
Hi Christian,

looks much better. Now it works. 
Regards,
Michael
